CREATE TABLE PAIS(
	Id_Pais INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE CIUDAD(
	Id_Ciudad INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE DIRECCION(
	Id_Direccion INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);


CREATE TABLE TIENDA(
	Id_Tienda INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Nombre_E VARCHAR(100) NOT NULL,
	Apellido_E VARCHAR(100) NOT NULL,
	Codigo_Postal INTEGER NOT NULL,
	Id_Pais INTEGER NOT NULL,
	Id_Ciudad INTEGER NOT NULL,
	Id_Direccion INTEGER NOT NULL,
    CONSTRAINT FK_TIENDA_PAIS FOREIGN KEY (Id_Pais) REFERENCES PAIS (Id_Pais),
    CONSTRAINT FK_TIENDA_CIUDAD FOREIGN KEY (Id_Ciudad) REFERENCES CIUDAD (Id_Ciudad),
    CONSTRAINT FK_TIENDA_DIRECCION FOREIGN KEY (Id_Direccion) REFERENCES DIRECCION (Id_Direccion)
);


CREATE TABLE CLIENTE(
	Id_Cliente INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	Activo CHAR(2) NOT NULL,
    Fecha_Registro TIMESTAMP,
	Tienda_Preferida VARCHAR(100) NOT NULL,
	Codigo_Postal INTEGER NOT NULL,
	Id_Pais INTEGER NOT NULL,
	Id_Ciudad INTEGER NOT NULL,
	Id_Direccion INTEGER NOT NULL,
    CONSTRAINT FK_CLIENTE_PAIS FOREIGN KEY (Id_Pais) REFERENCES PAIS (Id_Pais),
    CONSTRAINT FK_CLIENTE_CIUDAD FOREIGN KEY (Id_Ciudad) REFERENCES CIUDAD (Id_Ciudad),
    CONSTRAINT FK_CLIENTE_DIRECCION FOREIGN KEY (Id_Direccion) REFERENCES DIRECCION (Id_Direccion)
);

CREATE TABLE EMPLEADO(
	Id_Empleado INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	Activo CHAR(2) NOT NULL,
	Tienda_Asignado VARCHAR(100) NOT NULL,
	Usuario VARCHAR(100) NOT NULL,
	Contrasenia VARCHAR(100) NOT NULL,
	Codigo_Postal INTEGER NOT NULL,
	Id_Pais INTEGER NOT NULL,
	Id_Ciudad INTEGER NOT NULL,
	Id_Direccion INTEGER NOT NULL,
	Id_Tienda INTEGER NOT NULL,
    CONSTRAINT FK_EMPLEADO_PAIS FOREIGN KEY (Id_Pais) REFERENCES PAIS (Id_Pais),
    CONSTRAINT FK_EMPLEADO_CIUDAD FOREIGN KEY (Id_Ciudad) REFERENCES CIUDAD (Id_Ciudad),
    CONSTRAINT FK_EMPLEADO_DIRECCION FOREIGN KEY (Id_Direccion) REFERENCES DIRECCION (Id_Direccion),
    CONSTRAINT FK_EMPLEADO_TIENDA FOREIGN KEY (Id_Tienda) REFERENCES TIENDA (Id_Tienda)
);


CREATE TABLE RENTA(
	Id_Renta INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Fecha_Renta TIMESTAMP,
    Fecha_Retorno TIMESTAMP,
	Monto NUMBER(10,2) NOT NULL,
    Fecha_Pago TIMESTAMP,
	Id_Empleado INTEGER NOT NULL,
	Id_Cliente INTEGER NOT NULL,
    CONSTRAINT FK_RENTA_EMPLEADO FOREIGN KEY (Id_Empleado) REFERENCES EMPLEADO (Id_Empleado),
    CONSTRAINT FK_RENTA_CLIENTA FOREIGN KEY (Id_Cliente) REFERENCES CLIENTE (Id_Cliente)
);


CREATE TABLE PELICULA(
	Id_Pelicula INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(300) NOT NULL,
	Anio_Lanzamiento INTEGER NOT NULL,
	Duracion INTEGER NOT NULL,
	Costo_Daño NUMBER(10,2) NOT NULL,
	Dias_Renta INTEGER NOT NULL,
	Costo_Renta NUMBER(10,2) NOT NULL
);


CREATE TABLE INVENTARIO(
	Id_Inventario INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Tienda_Almacenada VARCHAR(100) NOT NULL,
	Id_Tienda INTEGER NOT NULL,
	Id_Pelicula INTEGER NOT NULL,
    CONSTRAINT FK_INVENTARIO_TIENDA FOREIGN KEY (Id_Tienda) REFERENCES TIENDA (Id_Tienda),
    CONSTRAINT FK_INVENTARIO_PELICULA FOREIGN KEY (Id_Pelicula) REFERENCES PELICULA (Id_Pelicula)
);


CREATE TABLE CATEGORIA(
	Id_Categoria INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IDIOMA(
	Id_Idioma INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE ACTOR(
	Id_Actor INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL
);

CREATE TABLE CLASIFICACION(
	Id_Clasificacion INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);


CREATE TABLE PELICULA_CATEGORIA(
	Id_Pelicula_Categoria INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Id_Pelicula INTEGER NOT NULL,
	Id_Categoria INTEGER NOT NULL,
    CONSTRAINT FK_PELICAT_PELICULA FOREIGN KEY (Id_Pelicula) REFERENCES PELICULA (Id_Pelicula),
    CONSTRAINT FK_PELICAT_CATEGORIA FOREIGN KEY (Id_Categoria) REFERENCES CATEGORIA (Id_Categoria)
);

CREATE TABLE PELICULA_IDIOMA(
	Id_Pelicula_Idioma INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Id_Pelicula INTEGER NOT NULL,
	Id_Idioma INTEGER NOT NULL,
    CONSTRAINT FK_PELIID_PELICULA FOREIGN KEY (Id_Pelicula) REFERENCES PELICULA (Id_Pelicula),
    CONSTRAINT FK_PELIID_IDIOMA FOREIGN KEY (Id_Idioma) REFERENCES IDIOMA (Id_Idioma)
);

CREATE TABLE PELICULA_ACTOR(
	Id_Pelicula_Actor INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Id_Pelicula INTEGER NOT NULL,
	Id_Actor INTEGER NOT NULL,
    CONSTRAINT FK_PELIACT_PELICULA FOREIGN KEY (Id_Pelicula) REFERENCES PELICULA (Id_Pelicula),
    CONSTRAINT FK_PELIACT_ACTOR FOREIGN KEY (Id_Actor) REFERENCES ACTOR (Id_Actor)
);

CREATE TABLE PELICULA_CLASIFICACION(
	Id_Pelicula_Categoria INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Id_Pelicula INTEGER NOT NULL,
	Id_Clasificacion INTEGER NOT NULL,
    CONSTRAINT FK_PELICLA_PELICULA FOREIGN KEY (Id_Pelicula) REFERENCES PELICULA (Id_Pelicula),
    CONSTRAINT FK_PELICLA_CLASIFICACION FOREIGN KEY (Id_Clasificacion) REFERENCES CLASIFICACION (Id_Clasificacion)
);


DROP TABLE PELICULA_CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE PELICULA_IDIOMA CASCADE CONSTRAINTS;
DROP TABLE PELICULA_ACTOR CASCADE CONSTRAINTS;
DROP TABLE PELICULA_CLASIFICACION CASCADE CONSTRAINTS;
DROP TABLE INVENTARIO CASCADE CONSTRAINTS;

DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE IDIOMA CASCADE CONSTRAINTS;
DROP TABLE ACTOR CASCADE CONSTRAINTS;
DROP TABLE CLASIFICACION CASCADE CONSTRAINTS;
DROP TABLE PELICULA CASCADE CONSTRAINTS;

DROP TABLE RENTA CASCADE CONSTRAINTS;

DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;

DROP TABLE TIENDA CASCADE CONSTRAINTS;

DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE DIRECCION CASCADE CONSTRAINTS;
