select count(*) as PAIS from  PAIS;
select count(*) as CIUDAD from  CIUDAD;
select count(*) as DIRECCION from  DIRECCION;
select count(*) as TIENDA from  TIENDA;
select count(*) as CLIENTE from  CLIENTE;
select count(*) as EMPLEADO from  EMPLEADO;
select count(*) as RENTA from  RENTA;
select count(*) as PELICULA from  PELICULA;
select count(*) as INVENTARIO from  INVENTARIO;
select count(*) as CATEGORIA from  CATEGORIA;
select count(*) as IDIOMA from  IDIOMA;
select count(*) as ACTOR from  ACTOR;
select count(*) as CLASIFICACION from  CLASIFICACION;
select count(*) as PELICULA_CATEGORIA from  PELICULA_CATEGORIA;
select count(*) as PELICULA_IDIOMA from  PELICULA_IDIOMA;
select count(*) as PELICULA_ACTOR from  PELICULA_ACTOR;
select count(*) as PELICULA_CLASIFICACION from  PELICULA_CLASIFICACION;

select count(*) as TEMPORAL from  TEMPORAL;